### ISSUE TITLE
ofxGrt not building in of0.93

### ISSUE THREAD

**Issue by batchku** [nickgillian/ofxGrt#16]
Hi Nick,

Something happened in the last 48 hours; the previous version of ofxGrt compiled in my ofx apps fine.  The version now gives an error for the "#include GRT/GRT.h" line, ofxGrt.h, saying "file not found".

Did something with paths changes in the last couple of days?

ali

**Comment by nickgillian** [comment]
Hi Ali,

This might be related to a bad pull-request-merge (that occurred yesterday).

This should be fixed now.

Can you try two things:

1) pull from the master branch to get the latest updates
2) run: **git submodule update** to get the latest backend GRT updates

I hope this fixes things.

**Comment by AndreasRef** [comment]
The same error happened to me today when trying to run the examples with the latest version of the addon in of0.98.

**Comment by AndreasRef** [comment]
The addon does not work anymore with this issue not fixed.. Could we do something to get it up an running again?

**Comment by AndreasRef** [comment]
Nicks advice does the trick:

git submodule init
    git submodule update

**Comment by kursor** [comment]
Installed today and same issue. Was fixed with @AndreasRef 's git tricks.
